/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\models\asteroid\Asteroid.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Asteroid({opacity, ...props}) {
  const { nodes, materials } = useGLTF('./models/asteroid/Asteroid.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Asteroids_Mesh.geometry} material={materials.Asteroids_Mat}
      transparent
      opacity={opacity} />
    </group>
  )
}

useGLTF.preload('./models/asteroid/Asteroid.glb')
