/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/dog/dog.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dog.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.circle001.geometry} material={materials.mat15} />
      <mesh geometry={nodes['circle000-Mesh'].geometry} material={materials.mat7} />
      <mesh geometry={nodes['circle000-Mesh_1'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['circle000-Mesh_2'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['circle000-Mesh_3'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['circle000-Mesh_4'].geometry} material={materials.mat19} />
    </group>
  )
}

useGLTF.preload('/dog.glb')
